title: a-learning-lab-course
description: Something amazing
template:
  repo: a-learning-lab-course-template
  name: a-learning-lab-course
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
